name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Pages
        uses: actions/configure-pages@v3
      
      - name: Create clean deployment directory
        run: |
          mkdir -p deployment
      
      - name: Copy all application files
        run: |
          # Copy only the necessary files directly
          cp tndr/index.html deployment/
          mkdir -p deployment/css deployment/js deployment/images
          cp tndr/css/*.css deployment/css/
          cp tndr/js/*.js deployment/js/
          
          # Copy additional assets
          if [ -d "tndr/images" ]; then
            cp -r tndr/images/* deployment/images/
          fi
          
          # Copy critical files to root
          cp tndr/manifest.json deployment/
          
          # Remove unwanted files
          rm -f deployment/README.md
      
      - name: Debug - List files in deployment
        run: |
          echo "Content of deployment directory:"
          find deployment -type f | sort
          
          echo "Content of root HTML file:"
          cat deployment/index.html | head -20
      
      - name: Setup index.html file
        run: |
          if [ ! -f "deployment/index.html" ]; then
            echo "ERROR: index.html is missing in deployment directory!"
            exit 1
          fi
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'deployment'
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2 